name: 'Cleanup test environment'
description: 'Restores changed Google contacts and renames log files'

inputs:
  TEST_RUNNER:
    description: 'The system used to run the scripts (python/docker)'
    required: true

runs:
  using: "composite"
  steps:
      - name: Restore original data
        run: python test/ChaosMonkey.py --restore
        shell: bash

      - name: Rename log files
        run: |
          mv logs/monkey.log logs/${{ inputs.TEST_RUNNER }}_monkey.log
          mv logs/setup.log logs/${{ inputs.TEST_RUNNER }}_setup.log
        shell: bash
