name: 'Setup test environment'
description: 'Sets up a new Monica instance, installs dependencies, and creates/gets sync tokens'

inputs:
  GOOGLE_TOKEN:
    description: 'The token.pickle file content (base64 string)'
    required: true
  MONICA_URL:
    description: 'The url to use for Monica connections'
    required: false
    default: http://localhost:8080/api

runs:
  using: "composite"
  steps:
    - name: Start new Monica instance
      run: docker-compose -f test/docker-compose-monica.yml up -d
      shell: bash

    - name: Create env file
      run: |
        touch .env data/token.pickle
        echo "${{ inputs.GOOGLE_TOKEN }}" >> data/token.pickle
        echo BASE_URL="${{ inputs.MONICA_URL }}" >> .env
      shell: bash

    - name: Install requirements
      run: python -m pip install --upgrade pip && pip install -r requirements.txt -r test/requirements.txt
      shell: bash

    - name: Create API token at Monica instance
      run: python test/SetupToken.py
      shell: bash

    - name: Create database file and monkey state
      run: python test/ChaosMonkey.py
      shell: bash

    - name: Set folder permissions for non-root containers
      run: sudo chmod 777 data logs -R
      shell: bash
