name: 'Setup test environment'
description: 'Sets up a new Monica instance, installs dependencies, and creates/gets sync tokens'

inputs:
  AZURE_TOKEN:
    description: 'An Azure SAS token'
    required: true
  ACCOUNT_URL:
    description: 'Your Azure blob storage account url'
    required: true

runs:
  using: "composite"
  steps:
    - name: Start new Monica instance
      run: docker-compose -f test/docker-compose-monica.yml up -d
      shell: bash

    - name: Install requirements
      run: python -m pip install --upgrade pip && pip install -r requirements.txt -r test/requirements.txt
      shell: bash

    - name: Download files from Azure Blob Storage
      run: python test/TransferFiles.py --download --files data/token.pickle
      shell: bash
      env:
        AZURE_TOKEN: ${{ inputs.AZURE_TOKEN }}
        ACCOUNT_URL: ${{ inputs.ACCOUNT_URL }}

    - name: Create API token at Monica instance
      run: python test/SetupToken.py
      shell: bash

    - name: Create database file and monkey state
      run: python test/ChaosMonkey.py
      shell: bash

    - name: Set folder permissions for non-root containers
      run: sudo chmod 777 data logs -R
      shell: bash
